/* Regenerate data/schedule.js.
 *
 *   node tools/schedule.js
 *
 * The daily answer used to be computed from the bank at page load, which meant
 * adding a grape silently reshuffled every past and present puzzle - a player
 * mid-game could have the answer swapped underneath them, and two people
 * playing "today" either side of a deploy got different wines. That makes a
 * challenge link meaningless.
 *
 * The schedule is now published data. Days up to and including today are
 * frozen and copied through untouched; only future days are regenerated from
 * the current bank, so new entries join the rotation from tomorrow onward and
 * never disturb what has already been played.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const { AROMA_FAMILY } = new Function(read('data/aromas.js') + '; return { AROMA_FAMILY };')();
const WINES = new Function(read('data/wines.js') + '; return WINES;')();

const pure = read('src/game.js').split('/* ---------- persistence ---------- */')[0];
const api = new Function('WINES', 'AROMA_FAMILY',
  pure + '; return { scheduledPick, dayNumber, LAUNCH_DAY };')(WINES, AROMA_FAMILY);

const HORIZON = 730;          /* two years of runway */
const NO_REPEAT_WITHIN = 25;  /* days before a wine may come round again */

const today = api.dayNumber();
const start = api.LAUNCH_DAY;

let existing = { start: start, days: [] };
try {
  existing = new Function(read('data/schedule.js') + '; return SCHEDULE;')();
} catch (e) {
  console.log('no existing schedule — starting fresh at day ' + start);
}

const names = new Set(WINES.map(w => w.name));
const days = [];

/* Frozen: everything already published stays exactly as it was. */
for (let day = existing.start; day <= today; day++) {
  const prior = existing.days[day - existing.start];
  if (prior && names.has(prior)) days[day - start] = prior;
}

/* A wine removed from the bank would leave a hole in history; fall back rather
 * than shifting every later day. */
for (let day = start; day <= today; day++) {
  if (!days[day - start]) days[day - start] = api.scheduledPick(day).name;
}

/* Future: regenerated from the current bank, avoiding anything used recently. */
for (let day = today + 1; day <= today + HORIZON; day++) {
  const recent = new Set(days.slice(Math.max(0, day - start - NO_REPEAT_WITHIN), day - start));
  let pick = api.scheduledPick(day);
  if (recent.has(pick.name)) {
    /* Walk forward through the same tier until something unused turns up. */
    for (let bump = 1; bump <= 60; bump++) {
      const alt = api.scheduledPick(day + bump * 7);
      if (!recent.has(alt.name)) { pick = alt; break; }
    }
  }
  days[day - start] = pick.name;
}

const out = `/* GENERATED by tools/schedule.js — do not edit by hand.
 *
 * The published daily schedule. Days up to and including the day this was last
 * generated are frozen: adding wines to the bank regenerates only the future,
 * so a puzzle already played never changes and everyone playing on a given day
 * gets the same answer regardless of when they loaded the page.
 *
 * Regenerate after adding entries:  node tools/schedule.js
 */

const SCHEDULE = {
  start: ${start},
  days: [
${days.map(n => '    ' + JSON.stringify(n)).join(',\n')}
  ]
};
`;

fs.writeFileSync(path.join(ROOT, 'data/schedule.js'), out);
console.log('schedule: day ' + start + ' → ' + (start + days.length - 1) +
            ' (' + days.length + ' days, ' + (today - start + 1) + ' frozen)');
